ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
EXECUTE IMMEDIATE 'CREATE USER coalertuser IDENTIFIED BY coalertpass';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01920 THEN NULL; 
ELSE RAISE;
END IF;
END;
/

GRANT CONNECT, RESOURCE TO coalertuser;
GRANT UNLIMITED TABLESPACE TO coalertuser;
