// <auto-generated />
using System;
using CoAlert.Infrastructure.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CoAlert.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250605165625_FixCommentDeleteBehavior")]
    partial class FixCommentDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoAlert.Domain.Entities.CategoriaDesastreEntity", b =>
                {
                    b.Property<long>("IdCategoriaDesastre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CATEGORIA_DESASTRE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCategoriaDesastre"));

                    b.Property<string>("DsCategoria")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_CATEGORIA");

                    b.Property<string>("NmTipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_TIPO");

                    b.Property<string>("NmTitulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_TITULO");

                    b.HasKey("IdCategoriaDesastre");

                    b.ToTable("CA_CATEGORIA_DESASTRE");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.ComentarioEntity", b =>
                {
                    b.Property<long>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_COMENTARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdComentario"));

                    b.Property<DateTime>("DtEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENVIO");

                    b.Property<long?>("IdComentarioParente")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_COMENTARIO_PARENTE");

                    b.Property<string>("NmConteudo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_CONTEUDO");

                    b.Property<long>("NrLikes")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("NR_LIKES");

                    b.Property<long>("PostagemId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_POSTAGEM");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdComentario");

                    b.HasIndex("IdComentarioParente");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CA_COMENTARIO");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.LikeEntity", b =>
                {
                    b.Property<long>("IdLike")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LIKE");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLike"));

                    b.Property<long?>("ComentarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_COMENTARIO");

                    b.Property<DateTime>("DtLike")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_LIKE");

                    b.Property<long?>("PostagemId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_POSTAGEM");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdLike");

                    b.HasIndex("ComentarioId");

                    b.HasIndex("PostagemId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CA_LIKE", t =>
                        {
                            t.HasCheckConstraint("CK_Like_PostOrComment", "(ID_POSTAGEM IS NULL AND ID_COMENTARIO IS NOT NULL) OR (ID_POSTAGEM IS NOT NULL AND ID_COMENTARIO IS NULL)");
                        });
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.LocalizacaoEntity", b =>
                {
                    b.Property<long>("IdLocalizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdLocalizacao"));

                    b.Property<string>("DsComplemento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DS_COMPLEMENTO");

                    b.Property<string>("NmBairro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_BAIRRO");

                    b.Property<string>("NmCidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_CIDADE");

                    b.Property<string>("NmEstado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("NmLogradouro")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_LOGRADOURO");

                    b.Property<string>("NmPais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_PAIS");

                    b.Property<string>("NrCep")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NR_CEP");

                    b.Property<int>("NrNumero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_NUMERO");

                    b.HasKey("IdLocalizacao");

                    b.ToTable("CA_LOCALIZACAO");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.PostagemEntity", b =>
                {
                    b.Property<long>("IdPostagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_POSTAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPostagem"));

                    b.Property<long>("CategoriaDesastreId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_CATEGORIA_DESASTRE");

                    b.Property<DateTime>("DtEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DT_ENVIO");

                    b.Property<long>("LocalizacaoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    b.Property<string>("NmConteudo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_CONTEUDO");

                    b.Property<string>("NmTitulo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_TITULO");

                    b.Property<int>("NrLikes")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NR_LIKES");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("IdPostagem");

                    b.HasIndex("CategoriaDesastreId");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CA_POSTAGEM");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<long>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdUsuario"));

                    b.Property<string>("NmEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_EMAIL");

                    b.Property<string>("NmUsuario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NM_USUARIO");

                    b.Property<string>("NrSenha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NR_SENHA");

                    b.HasKey("IdUsuario");

                    b.ToTable("CA_USUARIO");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.ComentarioEntity", b =>
                {
                    b.HasOne("CoAlert.Domain.Entities.ComentarioEntity", null)
                        .WithMany()
                        .HasForeignKey("IdComentarioParente")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoAlert.Domain.Entities.PostagemEntity", "Postagem")
                        .WithMany("Comentarios")
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoAlert.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postagem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.LikeEntity", b =>
                {
                    b.HasOne("CoAlert.Domain.Entities.ComentarioEntity", "Comentario")
                        .WithMany()
                        .HasForeignKey("ComentarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoAlert.Domain.Entities.PostagemEntity", "Postagem")
                        .WithMany()
                        .HasForeignKey("PostagemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoAlert.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comentario");

                    b.Navigation("Postagem");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.PostagemEntity", b =>
                {
                    b.HasOne("CoAlert.Domain.Entities.CategoriaDesastreEntity", "CategoriaDesastre")
                        .WithMany()
                        .HasForeignKey("CategoriaDesastreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoAlert.Domain.Entities.LocalizacaoEntity", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoAlert.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaDesastre");

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CoAlert.Domain.Entities.PostagemEntity", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
