FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

COPY ["CoAlert.csproj", "./"]
RUN dotnet restore "CoAlert.csproj"
COPY . .

RUN dotnet build "CoAlert.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
RUN dotnet publish "CoAlert.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /home/appuser/app

RUN adduser --disabled-password --gecos '' appuser

COPY --from=publish /app/publish ./

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENV ASPNETCORE_URLS=http://+:5024
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5024

USER appuser

ENTRYPOINT ["./entrypoint.sh"]
