FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release

WORKDIR /source

COPY ["CoAlert.csproj", "./"]
RUN dotnet restore "CoAlert.csproj"
COPY . .
RUN dotnet publish "CoAlert.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

RUN adduser --disabled-password --gecos '' appuser

WORKDIR /home/appuser/app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:5024
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5024

USER appuser

ENTRYPOINT ["dotnet", "CoAlert.dll"]
