FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

COPY ["CoAlert.csproj", "./"]
RUN dotnet restore "CoAlert.csproj"
COPY . .

RUN dotnet build "CoAlert.csproj" -c $BUILD_CONFIGURATION -o /app/build
RUN dotnet publish "CoAlert.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS final
ARG BUILD_CONFIGURATION=Release

RUN dotnet tool install --global dotnet-ef --version 8.0.0
ENV PATH="$PATH:/root/.dotnet/tools"

WORKDIR /app

COPY --from=build /app/publish ./

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENV ASPNETCORE_URLS=http://+:5024
ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5024

ENTRYPOINT ["./entrypoint.sh"]
